language: ruby
cache: bundler

services: mongodb

rvm:
  - 2.3.7

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - john+timeliness@carney.id.au
    on_failure: change
    on_success: never
